# Development server: loopback only. Change deliberately when deploying.
server-ip=127.0.0.1
server-port=25565
online-mode=true
pvp=true
gamemode=0
difficulty=2
max-players=24
allow-flight=true
allow-nether=false
enable-command-block=false
enable-query=false
enable-rcon=false
spawn-protection=0
view-distance=8
generate-structures=false
announce-player-achievements=false
level-name=world
level-type=FLAT
generator-settings=2;0;1;
motd=\u00a7cRushware Network \u00a78- \u00a77mc.rushware.cn
